[project]
name = "todo-cli"
version = "0.1.0"
description = "A simple todo CLI app"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "tabulate"
]

[project.scripts]
todo = "todo.cli:main"
